const ACTION_TYPE = {
    USER_SIGNUP: "USER_SIGNUP",
    PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
    USER_LOG_OUT: "USER_LOG_OUT",
    SHOW_PROFILE_CARD_POPUP: "SHOW_PROFILE_CARD_POPUP",
    MUSIC_UPLOAD_INFO: "MUSIC_UPLOAD_INFO",
    ALL_MUSIC_LIST: "ALL_MUSIC_LIST",
    FILE_UPLOAD_VALUE: "FILE_UPLOAD_VALUE",
    SELECTED_MUSIC: "SELECTED_MUSIC",
    ISPLAY: "ISPLAY",
    CART_PLAY_BUTTON: "CART_PLAY_BUTTON",
    SHOW_MUSIC_CART_PREV: "SHOW_MUSIC_CART_PREV",
    PREV_IMAGE_INFO: "PREV_IMAGE_INFO",
    SONG_LIKE: "SONG_LIKE",
    SONG_LIKE_HANDLER: "SONG_LIKE_HANDLER",
    ALL_SONGS_HANDLER: "ALL_SONGS_HANDLER",
    LIBRARY_SONG_HANDLER: "LIBRARY_SONG_HANDLER",
    SONGS_NAVIGATOR: "SONGS_NAVIGATOR",
};

export default ACTION_TYPE;
